/**
 * @packageDocumentation
 *
 * Entry point for **@figma-vars/hooks** — a modern, idiomatic React hooks library for Figma Variables via the REST API.
 *
 * @remarks
 * Exposes all providers, hooks, utilities, and types needed to build robust Figma variable dashboards, plugins, and design system tools.
 * Each export group below has its own summary and real-world usage example for rapid onboarding and type-safe integration.
 *
 * MIT Licensed. Author: Mark Learst.
 * Docs: {@link https://github.com/marklearst/figma-vars-hooks}
 */

/**
 * React context provider for Figma API authentication and file scoping.
 *
 * @remarks
 * Wrap your app in this provider to supply the Figma Personal Access Token and file key globally—all hooks and utilities will use this context.
 * This ensures seamless, type-safe access to the Figma REST API for all child components.
 *
 * @example
 * ```tsx
 * import { FigmaVarsProvider } from '@figma-vars/hooks';
 *
 * function App() {
 *   return (
 *     <FigmaVarsProvider token={process.env.FIGMA_TOKEN} fileKey="your-file-key">
 *       <YourComponent />
 *     </FigmaVarsProvider>
 *   );
 * }
 * ```
 */
export { FigmaVarsProvider } from './contexts'

/**
 * Core React hooks for interacting with Figma Variables.
 *
 * @remarks
 * Hooks for fetching, creating, updating, deleting, and bulk updating Figma variables—plus selectors for collections and modes.
 * All hooks share idiomatic return shapes and error handling for rapid UI and API integration.
 * Use these hooks to build dashboards, plugins, and design system tools with minimal boilerplate and maximum type safety.
 *
 * @see {@link https://www.figma.com/developers/api#variables | Figma Variables API}
 *
 * @example
 * ```tsx
 * import { useVariables, useCreateVariable } from '@figma-vars/hooks';
 *
 * function Example() {
 *   const { data, isLoading } = useVariables();
 *   const { mutate } = useCreateVariable();
 *   // Use the hooks in your component logic
 * }
 * ```
 */
export {
  useVariables,
  usePublishedVariables,
  useVariableCollections,
  useVariableModes,
  useVariableById,
  useCollectionById,
  useModesByCollection,
  useFigmaToken,
  useCreateVariable,
  useUpdateVariable,
  useDeleteVariable,
  useBulkUpdateVariables,
  useInvalidateVariables,
} from './hooks'

/**
 * Local design-token hooks (new in v5).
 *
 * @remarks
 * Consume the artifacts generated by `figma-vars build` — DTCG token files
 * plus a Resolver — directly in React. No Figma API access, no Personal
 * Access Token, works on every Figma plan, SSR-safe.
 *
 * @example
 * ```tsx
 * import { TokensProvider, useToken, useTheme } from '@figma-vars/hooks';
 *
 * function Brand() {
 *   const brand = useToken('semantic.color.bg.brand');
 *   const { setContext } = useTheme();
 *   return (
 *     <button
 *       style={{ background: brand.css ?? undefined }}
 *       onClick={() => setContext('semantic', 'dark')}>
 *       Go dark
 *     </button>
 *   );
 * }
 * ```
 */
export { TokensProvider, useTokens, useToken, useTheme } from './tokens'
export type {
  TokensProviderProps,
  TokensContextValue,
  UseTokenResult,
  UseThemeResult,
} from './tokens'

/**
 * Direct access to the Figma token context for advanced integrations.
 *
 * @remarks
 * `useFigmaTokenContext` returns the full provider context (token, fileKey, fallback data).
 * Most apps should prefer the higher-level hooks; this is for custom data layers.
 *
 * @example
 * ```tsx
 * import { useFigmaTokenContext } from '@figma-vars/hooks';
 * const { token, fileKey } = useFigmaTokenContext();
 * ```
 */
export { useFigmaTokenContext } from './contexts'

/**
 * Utility functions for Figma Variable management.
 *
 * @remarks
 * Helpers like `filterVariables` for searching and filtering variable lists, and error handling utilities. All utilities are stateless and type-safe—use for UI filtering, scripting, and dashboard logic.
 *
 * @example
 * ```ts
 * import { filterVariables, isFigmaApiError, getErrorStatus } from '@figma-vars/hooks';
 * const filtered = filterVariables(variables, { resolvedType: 'COLOR' });
 *
 * // Error handling
 * if (isFigmaApiError(error)) {
 *   console.log('Status:', error.statusCode);
 * }
 * ```
 */
export {
  filterVariables,
  withRetry,
  redactToken,
  isFigmaApiError,
  getErrorStatus,
  getErrorMessage,
  hasErrorStatus,
  isRateLimited,
  getRetryAfter,
  isLocalVariablesResponse,
  isPublishedVariablesResponse,
  validateFallbackData,
} from './utils'

/**
 * All official TypeScript types for advanced usage and type-safe integration.
 *
 * @remarks
 * All Figma domain models, mutation payloads/results, and provider context types—imported as needed for advanced TypeScript, API wrappers, plugins, and custom hooks.
 *
 * @example
 * ```ts
 * import type { FigmaVariable, CreateVariablePayload } from '@figma-vars/hooks';
 * ```
 */
export * from './types'
