export const MAX_GRAPH_LABEL_LENGTH = 256
export const MAX_GRAPH_ENCODED_LABEL_LENGTH = MAX_GRAPH_LABEL_LENGTH * 9
export const MAX_GRAPH_SOURCE_ID_LENGTH =
  'source:'.length + MAX_GRAPH_ENCODED_LABEL_LENGTH
export const MAX_GRAPH_QUALIFIED_ID_LENGTH =
  MAX_GRAPH_SOURCE_ID_LENGTH + '/token:'.length + MAX_GRAPH_ENCODED_LABEL_LENGTH
