import { useTokens } from './useTokens'

/**
 * Result of {@link useTheme}.
 *
 * @public
 */
export interface UseThemeResult {
  /** Active context per axis, e.g. `{ semantic: 'dark', density: 'compact' }`. */
  contexts: Record<string, string>
  /** Every context the resolver declares, per axis. */
  availableContexts: Record<string, string[]>
  /** Switch one axis: `setContext('semantic', 'dark')`. */
  setContext: (axis: string, context: string) => void
  /** Replace the entire selection at once. */
  setContexts: (contexts: Record<string, string>) => void
}

/**
 * Read and switch resolver contexts (Figma modes) at runtime.
 *
 * @remarks
 * Axes and context names come from the DTCG Resolver generated by
 * `figma-vars build` — a Figma collection "Theme" with modes Light/Dark
 * becomes `setContext('theme', 'dark')`.
 *
 * @example
 * ```tsx
 * const { contexts, availableContexts, setContext } = useTheme()
 * <button onClick={() => setContext('semantic', contexts.semantic === 'dark' ? 'light' : 'dark')}>
 *   Toggle theme
 * </button>
 * ```
 *
 * @public
 */
export function useTheme(): UseThemeResult {
  const { contexts, availableContexts, setContext, setContexts } = useTokens()
  return { contexts, availableContexts, setContext, setContexts }
}
