import { toDTCG, type ToDTCGOptions } from '../emit'
import { flattenTokens, listContexts } from '../resolve'
import { emitCss } from './css'
import { emitTailwind } from './tailwind'
import { emitTypescript } from './typescript'

/** A file to be written (CLI) or zipped (playground). @public */
export interface PipelineFile {
  /** Relative path inside the output directory. */
  path: string
  contents: string
}

/** Options for {@link buildPipeline}. @public */
export interface BuildPipelineOptions extends ToDTCGOptions {
  /** Which transformer config to scaffold. Default: `style-dictionary`. */
  transformer?: 'style-dictionary' | 'terrazzo' | 'none'
  /** Emit css/tokens.css. Default: true. */
  css?: boolean
  /** Emit css/tokens.tailwind.css (Tailwind v4 @theme). Default: true. */
  tailwind?: boolean
  /** Emit ts/tokens.ts. Default: true. */
  typescript?: boolean
  /** Emit a GitHub Actions workflow template. Default: true. */
  githubAction?: boolean
  /** Emit a README into the output directory. Default: true. */
  readme?: boolean
}

/** Summary statistics for reporting. @public */
export interface PipelineSummary {
  collections: number
  variables: number
  tokenFiles: number
  contexts: Record<string, string[]>
  files: string[]
}

/** Result of {@link buildPipeline}. @public */
export interface BuildPipelineResult {
  files: PipelineFile[]
  warnings: string[]
  summary: PipelineSummary
}

function serialize(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`
}

function styleDictionaryConfig(baseFiles: string[]): string {
  return `/**
 * Style Dictionary config generated by @figma-vars/cli.
 *
 * Sources are the base (default-mode) token files. Mode overrides are
 * handled by the generated css/tokens.css ([data-*] blocks) or by a
 * resolver-aware tool like Terrazzo; Style Dictionary support for the
 * DTCG Resolver spec is still evolving.
 *
 * Docs: https://styledictionary.com
 */
export default {
  source: [${baseFiles.map(f => `'tokens/${f}'`).join(', ')}],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'build/css/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
        },
      ],
    },
    js: {
      transformGroup: 'js',
      buildPath: 'build/js/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
        },
      ],
    },
  },
}
`
}

function terrazzoConfig(): string {
  return `/**
 * Terrazzo config generated by @figma-vars/cli.
 *
 * Terrazzo understands the DTCG Resolver document, so modes/themes come
 * through as resolver contexts. Requires @terrazzo/cli 2.x; on 1.x, point
 * \`tokens\` at ['./tokens/*.tokens.json'] instead.
 *
 * Docs: https://terrazzo.app/docs
 */
import { defineConfig } from '@terrazzo/cli'
import css from '@terrazzo/plugin-css'

export default defineConfig({
  tokens: './tokens/tokens.resolver.json',
  outDir: './build/',
  plugins: [
    css({
      filename: 'tokens.css',
    }),
  ],
})
`
}

function githubWorkflow(
  transformer: BuildPipelineOptions['transformer']
): string {
  const transformStep =
    transformer === 'terrazzo'
      ? `
      - name: Run Terrazzo
        run: npx @terrazzo/cli build`
      : transformer === 'style-dictionary'
        ? `
      - name: Run Style Dictionary
        run: npx style-dictionary build --config style-dictionary.config.mjs`
        : ''

  return `# Generated by @figma-vars/cli.
# Rebuilds the token pipeline whenever a new Figma variables export lands.
# If this file is not at the repository root, move it to .github/workflows/.
name: Design Tokens

on:
  push:
    paths:
      - 'variables.json'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build token pipeline
        run: npx @figma-vars/cli build variables.json --out .
${transformStep}

      - name: Commit generated tokens
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git diff --staged --quiet || git commit -m 'chore(tokens): rebuild from variables.json'
          git push
`
}

function pipelineReadme(
  summary: PipelineSummary,
  options: Required<
    Pick<
      BuildPipelineOptions,
      'transformer' | 'css' | 'tailwind' | 'typescript'
    >
  >
): string {
  const axes = Object.entries(summary.contexts)
  const contextDocs =
    axes.length > 0
      ? axes
          .map(
            ([axis, contexts]) =>
              `- \`${axis}\`: ${contexts.map(c => `\`${c}\``).join(', ')}`
          )
          .join('\n')
      : '- (no multi-mode collections)'

  return `# Design Tokens

Generated by [\`@figma-vars/cli\`](https://github.com/marklearst/figma-vars-hooks) from a Figma variables export.

## What's here

| Path | Purpose |
| --- | --- |
| \`tokens/*.tokens.json\` | DTCG 2025.10 token files, one per Figma collection (plus one per extra mode) |
| \`tokens/tokens.resolver.json\` | DTCG Resolver: how Figma modes combine into contexts |
${options.css ? '| `css/tokens.css` | CSS custom properties; theme via `data-*` attributes |\n' : ''}${options.tailwind ? '| `css/tokens.tailwind.css` | Tailwind CSS v4 `@theme` mapping |\n' : ''}${options.typescript ? '| `ts/tokens.ts` | Typed token paths, `var()` accessors, resolved values |\n' : ''}${options.transformer !== 'none' ? `| \`${options.transformer === 'terrazzo' ? 'terrazzo.config.mjs' : 'style-dictionary.config.mjs'}\` | Prewired ${options.transformer === 'terrazzo' ? 'Terrazzo' : 'Style Dictionary'} config |\n` : ''}
## Contexts

${contextDocs}

Switch contexts in the browser by setting data attributes:

\`\`\`html
<html data-semantic="dark">
\`\`\`

## Regenerate

\`\`\`sh
npx @figma-vars/cli build variables.json --out .
\`\`\`

Stats: ${summary.collections} collections, ${summary.variables} variables, ${summary.tokenFiles} token files.
`
}

/**
 * Build the complete token pipeline from a Figma variables JSON: DTCG token
 * files, resolver, CSS custom properties, Tailwind v4 theme, TypeScript
 * types, a transformer config, and a CI workflow — all as in-memory files.
 *
 * @remarks
 * Pure function: callers decide whether to write to disk (`figma-vars build`)
 * or zip in the browser (the playground).
 *
 * @public
 */
export function buildPipeline(
  input: unknown,
  options: BuildPipelineOptions = {}
): BuildPipelineResult {
  const resolved = {
    transformer: options.transformer ?? 'style-dictionary',
    css: options.css !== false,
    tailwind: options.tailwind !== false,
    typescript: options.typescript !== false,
    githubAction: options.githubAction !== false,
    readme: options.readme !== false,
  } as const

  const emitOptions: ToDTCGOptions = {}
  if (options.includeFigmaExtensions !== undefined) {
    emitOptions.includeFigmaExtensions = options.includeFigmaExtensions
  }
  if (options.resolverName !== undefined) {
    emitOptions.resolverName = options.resolverName
  }
  const dtcg = toDTCG(input, emitOptions)
  const files: PipelineFile[] = []

  const tokenFileNames = Object.keys(dtcg.files)
  for (const [name, doc] of Object.entries(dtcg.files)) {
    files.push({ path: `tokens/${name}`, contents: serialize(doc) })
  }
  files.push({
    path: `tokens/${dtcg.resolverFileName}`,
    contents: serialize(dtcg.resolver),
  })

  if (resolved.css) {
    files.push({
      path: 'css/tokens.css',
      contents: emitCss(dtcg.files, dtcg.resolver),
    })
  }
  if (resolved.tailwind) {
    files.push({
      path: 'css/tokens.tailwind.css',
      contents: emitTailwind(dtcg.files, dtcg.resolver),
    })
  }
  if (resolved.typescript) {
    files.push({
      path: 'ts/tokens.ts',
      contents: emitTypescript(dtcg.files, dtcg.resolver),
    })
  }

  const baseFiles = tokenFileNames.filter(
    name => name.split('.').length === 3 // "<collection>.tokens.json"
  )
  if (resolved.transformer === 'style-dictionary') {
    files.push({
      path: 'style-dictionary.config.mjs',
      contents: styleDictionaryConfig(baseFiles),
    })
  } else if (resolved.transformer === 'terrazzo') {
    files.push({ path: 'terrazzo.config.mjs', contents: terrazzoConfig() })
  }

  if (resolved.githubAction) {
    files.push({
      path: 'design-tokens.workflow.yml',
      contents: githubWorkflow(resolved.transformer),
    })
  }

  const summary: PipelineSummary = {
    collections: Object.keys(dtcg.resolver.sets ?? {}).length,
    variables: tokenFileNames
      .filter(name => name.split('.').length === 3)
      .reduce(
        (count, name) => count + flattenTokens(dtcg.files[name] ?? {}).length,
        0
      ),
    tokenFiles: tokenFileNames.length + 1,
    contexts: listContexts(dtcg.resolver),
    files: [],
  }

  if (resolved.readme) {
    files.push({
      path: 'README.md',
      contents: pipelineReadme(summary, resolved),
    })
  }

  summary.files = files.map(f => f.path)

  return { files, warnings: dtcg.warnings, summary }
}
