import { toDTCG, type ToDTCGOptions } from '../emit'
import { flattenTokens, listContexts } from '../resolve'
import { emitCss } from './css'
import { emitTailwind } from './tailwind'
import { emitTypescript } from './typescript'
import cliPackageManifest from '../../../cli/package.json' with { type: 'json' }

/** The pipeline returns each output file in this form. @public */
export interface PipelineFile {
  /** Relative path inside the output directory. */
  path: string
  contents: string
}

/** Options for {@link buildPipeline}. @public */
export interface BuildPipelineOptions extends ToDTCGOptions {
  /** Choose the transformer config to scaffold. Default: `style-dictionary`. */
  transformer?: 'style-dictionary' | 'terrazzo' | 'none'
  /** Emit css/tokens.css. Default: true. */
  css?: boolean
  /** Emit css/tokens.tailwind.css (Tailwind v4 @theme). Default: true. */
  tailwind?: boolean
  /** Emit ts/tokens.ts. Default: true. */
  typescript?: boolean
  /** Emit a GitHub Actions workflow template. Default: true. */
  githubAction?: boolean
  /** Emit a README into the output directory. Default: true. */
  readme?: boolean
}

/** Summary statistics for reporting. @public */
export interface PipelineSummary {
  collections: number
  variables: number
  tokenFiles: number
  contexts: Record<string, string[]>
  files: string[]
}

/** Result of {@link buildPipeline}. @public */
export interface BuildPipelineResult {
  files: PipelineFile[]
  warnings: string[]
  summary: PipelineSummary
}

function serialize(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`
}

function formatCount(count: number, singular: string): string {
  return `${count} ${singular}${count === 1 ? '' : 's'}`
}

function styleDictionaryConfig(baseFiles: string[]): string {
  return `/**
 * Style Dictionary config generated by @figmavars/cli.
 *
 * Sources are the base (default-mode) token files. Mode overrides are
 * handled by the generated css/tokens.css ([data-*] blocks) or by a
 * resolver-aware tool like Terrazzo; Style Dictionary support for the
 * DTCG Resolver spec is still evolving.
 *
 * Docs: https://styledictionary.com
 */
export default {
  source: [${baseFiles.map(f => `'tokens/${f}'`).join(', ')}],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'build/css/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
        },
      ],
    },
    js: {
      transformGroup: 'js',
      buildPath: 'build/js/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
        },
      ],
    },
  },
}
`
}

function terrazzoConfig(): string {
  return `/**
 * Terrazzo config generated by @figmavars/cli.
 *
 * Terrazzo understands the DTCG Resolver document, so modes/themes come
 * through as resolver contexts. Requires @terrazzo/cli 2.x; on 1.x, point
 * \`tokens\` at ['./tokens/*.tokens.json'] instead.
 *
 * Docs: https://terrazzo.app/docs
 */
import { defineConfig } from '@terrazzo/cli'
import css from '@terrazzo/plugin-css'

export default defineConfig({
  tokens: './tokens/tokens.resolver.json',
  outDir: './build/',
  plugins: [
    css({
      filename: 'tokens.css',
    }),
  ],
})
`
}

interface GeneratedWorkflowEntry {
  path: string
  kind: 'directory' | 'file'
}

function githubWorkflow(
  options: Required<
    Pick<
      BuildPipelineOptions,
      'transformer' | 'css' | 'tailwind' | 'typescript'
    >
  >
): string {
  const toolPackages = [`@figmavars/cli@${cliPackageManifest.version}`]
  const buildFlags = ['--no-github-action', '--no-readme']
  const generatedEntries: GeneratedWorkflowEntry[] = [
    { path: 'tokens', kind: 'directory' },
  ]

  if (options.css) {
    generatedEntries.push({ path: 'css/tokens.css', kind: 'file' })
  } else {
    buildFlags.push('--no-css')
  }
  if (options.tailwind) {
    generatedEntries.push({
      path: 'css/tokens.tailwind.css',
      kind: 'file',
    })
  } else {
    buildFlags.push('--no-tailwind')
  }
  if (options.typescript) {
    generatedEntries.push({ path: 'ts/tokens.ts', kind: 'file' })
  } else {
    buildFlags.push('--no-ts')
  }

  let transformStep = ''
  if (options.transformer === 'terrazzo') {
    toolPackages.push('@terrazzo/cli@2.4.0', '@terrazzo/plugin-css@2.4.0')
    buildFlags.push('--terrazzo')
    generatedEntries.push(
      { path: 'terrazzo.config.mjs', kind: 'file' },
      { path: 'build', kind: 'directory' }
    )
    transformStep = `
      - name: Run Terrazzo
        run: ./node_modules/.bin/terrazzo build`
  } else if (options.transformer === 'style-dictionary') {
    toolPackages.push('style-dictionary@5.5.0')
    buildFlags.push('--style-dictionary')
    generatedEntries.push(
      { path: 'style-dictionary.config.mjs', kind: 'file' },
      { path: 'build', kind: 'directory' }
    )
    transformStep = `
      - name: Run Style Dictionary
        run: ./node_modules/.bin/style-dictionary build --config style-dictionary.config.mjs`
  } else {
    buildFlags.push('--no-transformer')
  }

  const artifactPaths = generatedEntries
    .map(
      entry =>
        `            ${entry.path}${entry.kind === 'directory' ? '/' : ''}`
    )
    .join('\n')
  const artifactRootName = 'figmavars-artifact-root.json'
  const artifactRootContents = '{"schema":1}\n'
  const stagePaths = generatedEntries.map(entry => entry.path).join(' ')
  const serializedEntries = JSON.stringify(generatedEntries)

  return `# Generated by @figmavars/cli.
# Rebuilds the token pipeline whenever a new Figma variables export lands.
# If this file is not at the repository root, move it to .github/workflows/.
name: Design Tokens

on:
  push:
    branches: ['**']
    paths:
      - 'variables.json'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-tokens:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source revision
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: \${{ github.sha }}
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24.18.0

      - name: Install pinned token tools
        run: >-
          npm install --no-save --package-lock=false --ignore-scripts
          --audit=false --fund=false --registry=https://registry.npmjs.org
          ${toolPackages.join(' ')}

      - name: Build token pipeline
        run: ./node_modules/.bin/figma-vars build variables.json --out . ${buildFlags.join(' ')}
${transformStep}

      - name: Seal generated artifact root
        run: |
          rm -f ${artifactRootName}
          printf '%s\\n' '{"schema":1}' > ${artifactRootName}

      - name: Upload generated tokens
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: design-tokens-\${{ github.sha }}
          path: |
            ${artifactRootName}
${artifactPaths}
          if-no-files-found: error

  commit-tokens:
    needs: build-tokens
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source revision
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: \${{ github.sha }}
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24.18.0

      - name: Download generated tokens
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: design-tokens-\${{ github.sha }}
          path: .figmavars-generated

      - name: Validate and install generated tokens
        run: |
          node --input-type=module <<'NODE'
          import {
            cpSync,
            lstatSync,
            mkdirSync,
            readFileSync,
            readdirSync,
            rmSync,
          } from 'node:fs'
          import { basename, dirname, join, resolve, sep } from 'node:path'

          const entries = ${serializedEntries}
          const artifactRootName = ${JSON.stringify(artifactRootName)}
          const artifactRootContents = ${JSON.stringify(artifactRootContents)}
          const staging = resolve('.figmavars-generated')
          const workspace = resolve('.')
          const expectedTopLevel = [
            artifactRootName,
            ...new Set(entries.map(entry => entry.path.split('/')[0])),
          ].sort()
          const actualTopLevel = readdirSync(staging).sort()

          if (JSON.stringify(actualTopLevel) !== JSON.stringify(expectedTopLevel)) {
            throw new Error('generated artifact contains an unexpected top-level path')
          }

          const validateTree = target => {
            const stats = lstatSync(target)
            if (stats.isSymbolicLink()) {
              throw new Error('generated artifact must not contain symbolic links')
            }
            if (basename(target) === '.git') {
              throw new Error('generated artifact must not contain Git metadata')
            }
            if (stats.isDirectory()) {
              for (const child of readdirSync(target)) {
                validateTree(join(target, child))
              }
              return
            }
            if (!stats.isFile()) {
              throw new Error('generated artifact entries must be files or directories')
            }
          }
          validateTree(staging)
          const artifactRootPath = join(staging, artifactRootName)
          if (
            !lstatSync(artifactRootPath).isFile() ||
            readFileSync(artifactRootPath, 'utf8') !== artifactRootContents
          ) {
            throw new Error('generated artifact root anchor is invalid')
          }

          for (const entry of entries) {
            const source = join(staging, entry.path)
            const sourceStats = lstatSync(source)
            if (
              (entry.kind === 'directory' && !sourceStats.isDirectory()) ||
              (entry.kind === 'file' && !sourceStats.isFile())
            ) {
              throw new Error(
                'generated artifact entry has wrong type: ' + entry.path
              )
            }

            const target = resolve(entry.path)
            if (!target.startsWith(workspace + sep)) {
              throw new Error('generated artifact target escapes the workspace')
            }
            rmSync(target, { recursive: true, force: true })
            mkdirSync(dirname(target), { recursive: true })
            cpSync(source, target, { recursive: entry.kind === 'directory' })
          }
          NODE

      - name: Commit generated tokens
        run: |
          set -euo pipefail
          case "$GITHUB_REF" in
            refs/heads/*) ;;
            *) echo 'Refusing to push a non-branch ref' >&2; exit 1 ;;
          esac
          if [[ ! "$GITHUB_REPOSITORY" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]]; then
            echo 'Invalid GitHub repository identity' >&2
            exit 1
          fi
          if [[ ! "$GITHUB_SHA" =~ ^[a-f0-9]{40}$ ]]; then
            echo 'Invalid triggering revision' >&2
            exit 1
          fi
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all -- ${stagePaths}
          if git diff --staged --quiet; then
            exit 0
          fi

          ASKPASS=$(mktemp)
          trap 'rm -f "$ASKPASS"' EXIT
          cat >"$ASKPASS" <<'ASKPASS_SCRIPT'
          #!/bin/sh
          case "$1" in
            *Username*) printf '%s\\n' x-access-token ;;
            *Password*) printf '%s\\n' "$GITHUB_TOKEN" ;;
            *) exit 1 ;;
          esac
          ASKPASS_SCRIPT
          chmod 700 "$ASKPASS"
          REMOTE_URL="https://github.com/$GITHUB_REPOSITORY.git"
          REMOTE_SHA=$(GIT_ASKPASS="$ASKPASS" GIT_TERMINAL_PROMPT=0 git ls-remote --exit-code --refs "$REMOTE_URL" "$GITHUB_REF" | awk '{print $1}')
          if [[ "$REMOTE_SHA" != "$GITHUB_SHA" ]]; then
            echo 'The triggering branch moved; refusing to overwrite it' >&2
            exit 1
          fi

          git -c core.hooksPath=/dev/null commit -m 'chore(tokens): rebuild from variables.json'
          GIT_ASKPASS="$ASKPASS" GIT_TERMINAL_PROMPT=0 git -c core.hooksPath=/dev/null push "$REMOTE_URL" "HEAD:$GITHUB_REF"
        env:
          GITHUB_TOKEN: \${{ github.token }}
`
}

function pipelineReadme(
  summary: PipelineSummary,
  options: Required<
    Pick<
      BuildPipelineOptions,
      'transformer' | 'css' | 'tailwind' | 'typescript'
    >
  >
): string {
  const axes = Object.entries(summary.contexts)
  const contextDocs =
    axes.length > 0
      ? axes
          .map(
            ([axis, contexts]) =>
              `- \`${axis}\`: ${contexts.map(c => `\`${c}\``).join(', ')}`
          )
          .join('\n')
      : '- (no multi-mode collections)'

  return `# Design Tokens

Built from a Figma variables export with [\`@figmavars/cli\`](https://github.com/marklearst/figmavars).

The token JSON follows DTCG 2025.10 plus a documented boolean extension.

## Files

| Path | Purpose |
| --- | --- |
| \`tokens/*.tokens.json\` | Token files for each Figma collection and extra mode |
| \`tokens/tokens.resolver.json\` | Resolver mapping Figma modes to contexts |
${options.css ? '| `css/tokens.css` | CSS custom properties with `data-*` context selectors |\n' : ''}${options.tailwind ? '| `css/tokens.tailwind.css` | Tailwind CSS v4 `@theme` mapping |\n' : ''}${options.typescript ? '| `ts/tokens.ts` | Typed token paths, `var()` accessors, resolved values |\n' : ''}${options.transformer !== 'none' ? `| \`${options.transformer === 'terrazzo' ? 'terrazzo.config.mjs' : 'style-dictionary.config.mjs'}\` | ${options.transformer === 'terrazzo' ? 'Terrazzo' : 'Style Dictionary'} config |\n` : ''}
## Contexts

${contextDocs}

Set data attributes to select browser contexts:

\`\`\`html
<html data-semantic="dark">
\`\`\`

## Regenerate

\`\`\`sh
npx @figmavars/cli build variables.json --out .
\`\`\`

Stats: ${formatCount(summary.collections, 'collection')}, ${formatCount(summary.variables, 'variable')}, ${formatCount(summary.tokenFiles, 'token file')}.
`
}

/**
 * Build token JSON, a Resolver, CSS, Tailwind v4 mappings, TypeScript values,
 * transformer config, workflow, and README as in-memory files.
 *
 * @remarks
 * Pure function: callers decide whether to write to disk (`figma-vars build`)
 * or zip in the browser (the playground).
 *
 * @public
 */
export function buildPipeline(
  input: unknown,
  options: BuildPipelineOptions = {}
): BuildPipelineResult {
  const resolved = {
    transformer: options.transformer ?? 'style-dictionary',
    css: options.css !== false,
    tailwind: options.tailwind !== false,
    typescript: options.typescript !== false,
    githubAction: options.githubAction !== false,
    readme: options.readme !== false,
  } as const

  const emitOptions: ToDTCGOptions = {}
  if (options.includeFigmaExtensions !== undefined) {
    emitOptions.includeFigmaExtensions = options.includeFigmaExtensions
  }
  if (options.resolverName !== undefined) {
    emitOptions.resolverName = options.resolverName
  }
  const dtcg = toDTCG(input, emitOptions)
  const files: PipelineFile[] = []

  const tokenFileNames = Object.keys(dtcg.files)
  for (const [name, doc] of Object.entries(dtcg.files)) {
    files.push({ path: `tokens/${name}`, contents: serialize(doc) })
  }
  files.push({
    path: `tokens/${dtcg.resolverFileName}`,
    contents: serialize(dtcg.resolver),
  })

  if (resolved.css) {
    files.push({
      path: 'css/tokens.css',
      contents: emitCss(dtcg.files, dtcg.resolver),
    })
  }
  if (resolved.tailwind) {
    files.push({
      path: 'css/tokens.tailwind.css',
      contents: emitTailwind(dtcg.files, dtcg.resolver),
    })
  }
  if (resolved.typescript) {
    files.push({
      path: 'ts/tokens.ts',
      contents: emitTypescript(dtcg.files, dtcg.resolver),
    })
  }

  const baseFiles = tokenFileNames.filter(
    name => name.split('.').length === 3 // "<collection>.tokens.json"
  )
  if (resolved.transformer === 'style-dictionary') {
    files.push({
      path: 'style-dictionary.config.mjs',
      contents: styleDictionaryConfig(baseFiles),
    })
  } else if (resolved.transformer === 'terrazzo') {
    files.push({ path: 'terrazzo.config.mjs', contents: terrazzoConfig() })
  }

  if (resolved.githubAction) {
    files.push({
      path: 'design-tokens.workflow.yml',
      contents: githubWorkflow(resolved),
    })
  }

  const summary: PipelineSummary = {
    collections: Object.keys(dtcg.resolver.sets ?? {}).length,
    variables: tokenFileNames
      .filter(name => name.split('.').length === 3)
      .reduce(
        (count, name) => count + flattenTokens(dtcg.files[name] ?? {}).length,
        0
      ),
    tokenFiles: tokenFileNames.length + 1,
    contexts: listContexts(dtcg.resolver),
    files: [],
  }

  if (resolved.readme) {
    files.push({
      path: 'README.md',
      contents: pipelineReadme(summary, resolved),
    })
  }

  summary.files = files.map(f => f.path)

  return { files, warnings: dtcg.warnings, summary }
}
