import type {
  DTCGDocument,
  DTCGToken,
  DTCGTokenValue,
  ResolverDocument,
} from '../types'
import { isReferenceValue } from '../types'
import {
  applyResolver,
  flattenTokens,
  listContexts,
  type FlatToken,
} from '../resolve'

/** Convert a dot path to a CSS custom property name. @public */
export function cssVarName(path: string): string {
  return `--${path
    .split('.')
    .map(segment =>
      segment
        .trim()
        .replace(/[^a-zA-Z0-9-]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .toLowerCase()
    )
    .filter(s => s.length > 0)
    .join('-')}`
}

function quoteIfNeeded(value: string): string {
  return /[\s'"]/.test(value) ? `'${value.replace(/'/g, "\\'")}'` : value
}

/**
 * Format a DTCG token value as CSS. References become `var(--...)` so the
 * alias graph survives into the stylesheet. Returns `null` for values with
 * no CSS representation (booleans).
 *
 * @public
 */
export function cssValue(value: DTCGTokenValue): string | null {
  if (isReferenceValue(value)) {
    return `var(${cssVarName(value.slice(1, -1))})`
  }
  if (typeof value === 'number') {
    return String(value)
  }
  if (typeof value === 'string') {
    return quoteIfNeeded(value)
  }
  if (typeof value === 'boolean') {
    return null
  }
  if ('colorSpace' in value) {
    const alpha = value.alpha ?? 1
    if (alpha < 1) {
      const [r, g, b] = value.components
      return `rgb(${Math.round(r * 255)} ${Math.round(g * 255)} ${Math.round(b * 255)} / ${alpha})`
    }
    if (value.hex) {
      return value.hex
    }
    const [r, g, b] = value.components
    return `rgb(${Math.round(r * 255)} ${Math.round(g * 255)} ${Math.round(b * 255)})`
  }
  if ('unit' in value) {
    return `${value.value}${value.unit}`
  }
  return null
}

function declarations(flat: FlatToken[], indent: string): string[] {
  const lines: string[] = []
  for (const { path, token } of flat) {
    const value = cssValue(token.$value)
    if (value === null) {
      continue
    }
    lines.push(`${indent}${cssVarName(path)}: ${value};`)
  }
  return lines
}

function tokensEqual(
  a: DTCGToken | undefined,
  b: DTCGToken | undefined
): boolean {
  return JSON.stringify(a?.$value) === JSON.stringify(b?.$value)
}

/** Options for {@link emitCss}. @public */
export interface EmitCssOptions {
  /**
   * Header comment for the generated stylesheet.
   */
  banner?: string
}

/**
 * Emit CSS custom properties from token files and a Resolver.
 *
 * `:root` contains the default values. A `[data-<axis>='<context>']` block
 * contains values that change for a non-default context.
 *
 * @public
 */
export function emitCss(
  files: Record<string, DTCGDocument>,
  resolver: ResolverDocument,
  options: EmitCssOptions = {}
): string {
  const banner =
    options.banner ??
    'Generated by @figmavars/dtcg. Default contexts in :root; switch themes by setting data attributes, e.g. <html data-semantic="dark">.'

  const lines: string[] = [`/* ${banner} */`, '']

  const defaultDoc = applyResolver(files, resolver)
  const defaultFlat = flattenTokens(defaultDoc)
  const defaultByPath = new Map(defaultFlat.map(f => [f.path, f.token]))

  lines.push(':root {', ...declarations(defaultFlat, '  '), '}')

  const axes = listContexts(resolver)
  for (const [axis, contexts] of Object.entries(axes)) {
    const defaultContext = resolver.modifiers?.[axis]?.default ?? contexts[0]
    for (const context of contexts) {
      if (context === defaultContext) {
        continue
      }
      const contextDoc = applyResolver(files, resolver, { [axis]: context })
      const contextFlat = flattenTokens(contextDoc)
      const changed = contextFlat.filter(
        f => !tokensEqual(defaultByPath.get(f.path), f.token)
      )
      if (changed.length === 0) {
        continue
      }
      lines.push(
        '',
        `[data-${axis}='${context}'] {`,
        ...declarations(changed, '  '),
        '}'
      )
    }
  }

  lines.push('')
  return lines.join('\n')
}
