import type { DTCGDocument, ResolverDocument } from '../types'
import { applyResolver, flattenTokens } from '../resolve'
import { cssVarName } from './css'

const NAMESPACE_NOISE: Record<string, Set<string>> = {
  color: new Set(['color', 'colors']),
  radius: new Set(['radius', 'radii']),
  spacing: new Set(['space', 'spacing']),
  font: new Set(['font', 'fonts', 'family', 'typeface']),
  'font-weight': new Set(['font', 'weight']),
}

function tailwindName(path: string, namespace: string): string {
  const segments = path.split('.')
  // Drop the collection prefix, then leading segments that just repeat the
  // namespace (e.g. semantic.color.bg.brand -> bg-brand under --color-*,
  // primitives.font.family.sans -> sans under --font-*).
  let rest = segments.slice(1)
  const noise = NAMESPACE_NOISE[namespace] ?? new Set([namespace])
  while (rest.length > 1 && rest[0] && noise.has(rest[0].toLowerCase())) {
    rest = rest.slice(1)
  }
  const slug = rest
    .map(s =>
      s
        .replace(/[^a-zA-Z0-9-]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .toLowerCase()
    )
    .filter(s => s.length > 0)
    .join('-')
  return slug.length > 0 ? slug : 'default'
}

/**
 * Emit a Tailwind CSS v4 `@theme inline` file that maps design tokens onto
 * Tailwind's theme namespaces, referencing the custom properties from the
 * generated `tokens.css` so mode switching keeps working.
 *
 * @remarks
 * Mapping: `color` → `--color-*`; `dimension` → `--radius-*` when the path
 * mentions radius, otherwise `--spacing-*`; `fontFamily` → `--font-*`;
 * `fontWeight` → `--font-weight-*`. Other types have no Tailwind namespace
 * and are skipped.
 *
 * @public
 */
export function emitTailwind(
  files: Record<string, DTCGDocument>,
  resolver: ResolverDocument
): string {
  const flat = flattenTokens(applyResolver(files, resolver))
  const used = new Set<string>()
  const lines: string[] = [
    '/* Generated by @figma-vars/dtcg for Tailwind CSS v4.',
    '   Import tokens.css BEFORE this file so the referenced variables exist:',
    "     @import './tokens.css';",
    "     @import './tokens.tailwind.css';  */",
    '',
    '@theme inline {',
  ]

  const entries: string[] = []
  for (const { path, token } of flat) {
    let namespace: string | null = null
    switch (token.$type) {
      case 'color':
        namespace = 'color'
        break
      case 'dimension':
        namespace = /(^|[./-])radius/i.test(path) ? 'radius' : 'spacing'
        break
      case 'fontFamily':
        namespace = 'font'
        break
      case 'fontWeight':
        namespace = 'font-weight'
        break
      default:
        namespace = null
    }
    if (namespace === null) {
      continue
    }
    let name = `--${namespace}-${tailwindName(path, namespace)}`
    if (used.has(name)) {
      const collection = path.split('.')[0] ?? 'tokens'
      name = `--${namespace}-${collection}-${tailwindName(path, namespace)}`
    }
    if (used.has(name)) {
      continue
    }
    used.add(name)
    entries.push(`  ${name}: var(${cssVarName(path)});`)
  }

  lines.push(...entries, '}', '')
  return lines.join('\n')
}
