import type { DTCGDocument, ResolverDocument } from '../types'
import { applyResolver, flattenTokens, resolveTokenValues } from '../resolve'
import { cssVarName, cssValue } from './css'

/**
 * Emit a typed TypeScript module for the generated tokens: a `TokenPath`
 * union, a map of CSS `var()` accessors, and the resolved default-context
 * values.
 *
 * @public
 */
export function emitTypescript(
  files: Record<string, DTCGDocument>,
  resolver: ResolverDocument
): string {
  const merged = applyResolver(files, resolver)
  const flat = flattenTokens(merged)
  const resolved = resolveTokenValues(flat)

  const paths = flat.map(f => f.path).sort()

  const lines: string[] = [
    '/**',
    ' * Generated by @figma-vars/cli. Do not edit by hand.',
    ' * Values reflect the default context of every modifier axis.',
    ' */',
    '',
    'export type TokenPath =',
  ]
  for (const path of paths) {
    lines.push(`  | '${path}'`)
  }
  lines.push('')

  lines.push(
    '/** CSS var() accessors for each token (theme-aware at runtime). */'
  )
  lines.push('export const tokenVars = {')
  for (const path of paths) {
    lines.push(`  '${path}': 'var(${cssVarName(path)})',`)
  }
  lines.push('} as const satisfies Record<TokenPath, string>')
  lines.push('')

  lines.push('/** Resolved default-context values, formatted for CSS. */')
  lines.push('export const tokenValues = {')
  for (const path of paths) {
    const value = resolved.get(path)
    const css = value === undefined ? null : cssValue(value)
    const literal =
      css !== null
        ? `'${css.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
        : JSON.stringify(value)
    lines.push(`  '${path}': ${literal},`)
  }
  lines.push('} as const')
  lines.push('')

  return lines.join('\n')
}
